#!/usr/bin/env python2.7

import os
import re
import subprocess
import sys

VERBOSE = 0

BASE_PREFIX = '__block_base__'
TIP_PREFIX = '__block_tip__'
VERSION = '0.2'
VERSION_STR = 'git-block v' + VERSION

####

def run_git(*args):
    args = ['git'] + list(args)

    if VERBOSE >= 1:
        print >>sys.stderr, '    <' + ' '.join(args) + '>'

    try:
        ret = subprocess.check_output(args, stderr=subprocess.STDOUT).splitlines()
        if VERBOSE >= 2:
            for x in ret:
                print >>sys.stderr, '        >' + x
        return ret
    except subprocess.CalledProcessError as e:
        if VERBOSE >= 1:
            for x in e.output.splitlines():
                print >>sys.stderr, '        !' + x
        raise


def popen_git(args, stdin=None, stdout=None, stderr=None):
    args = ['git'] + list(args)

    if VERBOSE >= 1:
        print >>sys.stderr, '    <<' + ' '.join(args) + '>>'

    p = subprocess.Popen(args, stdin=stdin, stdout=stdout, stderr=stderr)
    return p

####

class GitRollback():
    def __init__(self, cmd_name):
        self.cmd_name = cmd_name
        self.rollback_list = []
        return


    def add(self, *git_args):
        self.rollback_list.append(git_args)
        return


    def rollback(self, ex_val):
        if not self.rollback_list:
            return # Nothing to roll back.

        print >>sys.stderr, 'Attempting rollback...'

        try:
            for x in reversed(self.rollback_list):
                run_git(*x)
                continue
            return True
        except subprocess.CalledProcessError as e:
            print >>sys.stderr, 'ERROR: Rollback failed:'
            print >>sys.stderr, e.output
            exit(-1) # The world is broken.
        return


    def __enter__(self):
        return self


    def __exit__(self, ex_type, ex_val, ex_traceback):
        if ex_type != subprocess.CalledProcessError:
            return # Pass it on.

        print >>sys.stderr, 'ERROR: `{}` failed:'.format(self.cmd_name)
        for x in ex_val.output.splitlines():
            print >>sys.stderr, x

        self.rollback(ex_val)
        exit(1)

####

def main(args):
    global VERBOSE
    if args:
        if args[0] == '-v':
            VERBOSE = 1
            args.pop(0)
        elif args[0] == '-vv':
            VERBOSE = 2
            args.pop(0)

    ####

    cur_branch = run_git('rev-parse', '--abbrev-ref', 'HEAD')[0].strip()

    cur_block = None
    if cur_branch.startswith(TIP_PREFIX):
        cur_block = cur_branch[len(TIP_PREFIX):]

    ####

    branches = [x[2:] for x in run_git('branch')]
    branches = set(branches)

    bases = set()
    tips = set()
    for x in branches:
        if x.startswith(BASE_PREFIX):
            bases.add(x[len(BASE_PREFIX):])
            continue

        if x.startswith(TIP_PREFIX):
            tips.add(x[len(TIP_PREFIX):])
            continue
        continue

    blocks = bases.intersection(tips)

    ####

    if not args:
        for x in sorted(blocks):
            prefix = '  '
            if x == cur_block:
                prefix = '* '
            print prefix + x
            continue
        return 0

    cmd = args.pop(0)
    if cmd == '--version':
        print VERSION_STR
        return 0


    if cmd == '--help':
        print VERSION_STR
        print 'Commands:'
        print '  --version'
        print '  <> | Lists blocks'
        print '  new <name>'
        print '  delete <name>'
        print '  <name> | Checks out a block'
        return 0

    ####

    if cmd == 'clean':
        def delete_orphans(type_name, type_set, type_prefix):
            for x in type_set:
                if x in blocks:
                    continue

                branch_name = type_prefix + x
                try:
                    run_git('branch', '-D', branch_name)
                    print >>sys.stderr, 'Deleted orphaned {} \'{}\''.format(type_name, branch_name)
                except subprocess.CalledProcessError:
                    print >>sys.stderr, 'Failed to delete orphaned {} \'{}\''.format(type_name, branch_name)
                    pass
                continue
            return

        delete_orphans('base', bases, BASE_PREFIX)
        delete_orphans('tip', tips, TIP_PREFIX)
        return 0

    ####

    if cmd == 'new':
        switch_to_tip = False

        name = None
        start_point = 'HEAD'
        while args:
            x = args.pop(0)
            if x == '-b':
                switch_to_tip = True
                continue

            if not name:
                name = x
                continue

            start_point = x
            break
        else:
            if not name:
                print >>sys.stderr, 'ERROR: Not enough args'
                return 1

        if name == 'HEAD':
            print >>sys.stderr, 'ERROR: Block name \'{}\' is reserved'.format(name)
            return 1

        if name in blocks:
            print >>sys.stderr, 'ERROR: Block \'{}\' already exists'.format(name)
            return 1

        if start_point in blocks:
            start_point = TIP_PREFIX + start_point

        base_name = BASE_PREFIX + name
        tip_name = TIP_PREFIX + name

        with GitRollback(cmd) as r:
            run_git('branch', base_name, start_point)
            r.add('branch', '-D', base_name)

            if switch_to_tip:
                run_git('checkout', '-b', tip_name)
            else:
                run_git('branch', tip_name)
        return 0

    ####

    if cmd == 'delete':
        while args:
            x = args.pop(0)
            name = x
            break
        else:
            print >>sys.stderr, 'ERROR: Not enough args'
            return 1

        if not name in blocks:
            print >>sys.stderr, 'ERROR: Block \'{}\' does not exist'.format(name)
            return 1

        if name == cur_block:
            print >>sys.stderr, 'ERROR: Block \'{}\' is active'.format(name)
            return 1

        with GitRollback(cmd):
            if name in tips:
                run_git('branch', '-D', TIP_PREFIX + name)
            if name in bases:
                run_git('branch', '-D', BASE_PREFIX + name)
        print 'Deleted block \'{}\''.format(name)
        return 0

    ####

    if cmd == 'show':
        target = cur_block
        while args:
            x = args.pop(0)
            target = x
            break

        if not target:
            print >>sys.stderr, 'ERROR: No block is active'
            return 1

        if target not in blocks:
            print >>sys.stderr, 'ERROR: Unknown block \'{}\''.format(target)
            return 1

        range_arg = '{}..{}'.format(BASE_PREFIX+target, TIP_PREFIX+target)
        p = popen_git(('--no-pager', 'log', range_arg))
        p.communicate()
        return p.returncode

    ####

    if cmd == 'base' or cmd == 'tip':
        target = cur_block
        while args:
            x = args.pop(0)
            target = x
            break

        if not target:
            print >>sys.stderr, 'ERROR: No block is active'
            return 1

        if target not in blocks:
            print >>sys.stderr, 'ERROR: Unknown block \'{}\''.format(target)
            return 1

        if cmd == 'base':
            print BASE_PREFIX+target
        else:
            print TIP_PREFIX+target
        return 0

    ####

    if cmd == 'mozreview':
        if not cur_block:
            print >>sys.stderr, 'ERROR: No block is active'
            return 1

        p = popen_git(('mozreview', 'push', BASE_PREFIX+cur_block + '..'))
        p.communicate()
        return p.returncode

    ####

    if cmd == 'rebase':
        return rebase(blocks, cur_block, args)

    ####

    if cmd not in blocks:
        print >>sys.stderr, 'ERROR: Unknown block or command \'{}\''.format(cmd)
        return 1
    name = cmd

    if name == cur_block:
        print >>sys.stderr, 'Already on block \'{}\''.format(name)
        return 1

    tip_name = TIP_PREFIX + name
    with GitRollback('checkout') as r:
        run_git('checkout', tip_name)
        print 'Switched to block \'{}\''.format(name)

    return 0

####

def rebase(blocks, cur_block, args):
    git_dir = '.git'
    assert os.path.exists(git_dir)

    if os.path.isfile(git_dir):
        with open(git_dir) as f:
            git_dir = f.readlines()[0].strip()
        (_, git_dir) = git_dir.split('gitdir: ', 1)
        git_dir = os.path.normpath(git_dir)

    assert os.path.exists(git_dir)

    rebase_dir = os.path.join(git_dir, 'rebase-apply')
    if os.path.exists(rebase_dir):
        return in_rebase(blocks, args, rebase_dir)

    rebase_dir = os.path.join(git_dir, 'rebase-merge')
    if os.path.exists(rebase_dir):
        return in_rebase(blocks, args, rebase_dir)

    ####

    if not cur_block:
        print >>sys.stderr, 'ERROR: No block is active for rebase'
        return 1

    base_name = BASE_PREFIX + cur_block
    tip_name = TIP_PREFIX + cur_block

    ####

    absorb_already_applied = False
    while args:
        x = args.pop(0)
        if x == '-a':
            absorb_already_applied = True
            continue

        onto = x

        if onto.startswith('-'):
            print >>sys.stderr, 'ERROR: Invalid subcommand \'{}\''.format(target)
            return 1

        if onto in blocks:
            onto = TIP_PREFIX + onto

        break
    else:
        if absorb_already_applied:
            print >>sys.stderr, 'ERROR: Not enough args'
            return 1

        onto = base_name


    try:
        onto_rev = run_git('rev-parse', onto)[0].strip() # Validate and save for later.
    except subprocess.CalledProcessError:
        print >>sys.stderr, 'ERROR: Bad `onto`: \'{}\''.format(onto)
        return 1

    rebase_args = ['rebase', '--onto', onto, base_name, tip_name] # Don't need onto_rev here.
    if not absorb_already_applied:
        rebase_args[1:1] = ['-i']

    p = popen_git(rebase_args)
    p.wait()
    if p.returncode != 0:
        return p.returncode

    run_git('branch', '-f', base_name, onto_rev)
    return 0

####

def in_rebase(blocks, args, rebase_dir):
    def read_rebase_file_line(rebase_dir, file_name):
        path = os.path.join(rebase_dir, file_name)
        with open(path, 'r') as f:
            line = f.readlines()[0].rstrip()

        if VERBOSE >= 2:
            print >>sys.stderr, '{}: \'{}\''.format(path, line)

        return line

    head_name = read_rebase_file_line(rebase_dir, 'head-name')
    onto = read_rebase_file_line(rebase_dir, 'onto')

    HEAD_NAME_PREFIX = 'refs/heads/' + TIP_PREFIX
    assert head_name.startswith(HEAD_NAME_PREFIX)
    cur_block = head_name[len(HEAD_NAME_PREFIX):]

    if cur_block not in blocks:
        print >>sys.stderr, 'ERROR: No block is active during current rebase'
        return 1

    ####

    while args:
        x = args.pop(0)
        cmd = x
        break
    else:
        print >>sys.stderr, 'ERROR: Not enough args'
        return 1

    if cmd == '--abort':
        run_git('rebase', '--abort')
        return 0

    if cmd.startswith('--cont'):
        p = popen_git(('rebase', '--continue'))
        p.communicate()
        if p.returncode != 0:
            return 1

        run_git('branch', '-f', BASE_PREFIX + cur_block, onto)
        return 0

    print >>sys.stderr, 'ERROR: Unrecognized subcommand \'{}\''.format(cmd)
    return 1

####

if __name__ == '__main__':
    exit(main(sys.argv[1:]))
